# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Mr. Gaytán
tagline:          
description:      'Software Developer and frustrated Graphic Designer'
url:              http://mrgaytan.github.io
baseurl:          /

author:
  name:           'Israel Gaytán'
  url:            https://twitter.com/mrgaytan

paginate:         5

github:
  repo:           https://github.com/MrGaytan
