# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            
tagline:          
description:      'Un Desarollador de Software cualquiera y Diseñado Gráfico <strike>fracasado</strike> frustrado.'
url:              http://mrgaytan.github.io
baseurl:          /

author:
  name:           'Israel Gaytán'
  url:            https://twitter.com/mrgaytan

paginate:         5

github:
  repo:           https://github.com/MrGaytan
