# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Mr. Gayt치n
tagline:          
description:      'Desarollador de Software (un programador cualquiera) y Dise침ador Gr치fico frustrado.'
url:              http://mrgaytan.github.io
baseurl:          /

author:
  name:           'Israel Gayt치n'
  url:            https://twitter.com/mrgaytan

paginate:         5

github:
  repo:           https://github.com/MrGaytan
