# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            <img src="../public/mrgaytanLogo.png" />
tagline:          
description:      'Desarollador de Software (un programaor cualquiera) y Diseñador Gráfico frustrado.'
url:              http://mrgaytan.github.io
baseurl:          /

author:
  name:           'Israel Gaytán'
  url:            https://twitter.com/mrgaytan

paginate:         5

github:
  repo:           https://github.com/MrGaytan
